concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-77e8b39c960e"
  url = "http://gitlab.localhost:8081/"
  id = 2
  token = "glrt-EuyAzr-C6NSus7NaV6T-"
  token_obtained_at = 2024-11-09T12:33:22Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"
    privileged = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode = "host"
  [runners.cache]
    Insecure = false
